# Generated by Django 2.0.10 on 2019-02-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carritocompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
