# Generated by Django 2.0.10 on 2019-02-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20190210_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='identificador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
