# Generated by Django 2.0.10 on 2019-02-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20190216_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='identificador',
            field=models.IntegerField(null=True),
        ),
    ]
